### ISSUE TITLE
Implicit derived object does prevent calling the super()

### ISSUE THREAD

**Issue by ManolitoSnell-INDG** [humboldtjs/HumboldtJSLibrary#11]
**Example**
When a object has not been derived from anything, in Actionscript the object is implicitly being derived from `Object`, hereby making a `super()` call is completly valid.

``` actionscript
class A
{
        public function A()
        {
            // Calling the super now will trigger a Huboldt fault...
             super();
        }
}

class A extends B
{
        public function A()
        {
            // OK
             super();
        }
}
```

**Actual result**
Class A will trigger an runtime error.

**Expected result**
Actionscript behaviour, so calling Class A should not trigger a runtime error.

**Comment by humboldtjs** [comment]
Fixed this!
