### ISSUE TITLE
Animator class doesnt do the vendor prefixing on properties

### ISSUE THREAD

**Issue by martijndeb** [humboldtjs/HumboldtJSLibrary#2]
If we animatePropertyTo "-opacity" we get the following error. Easily workarounded, but it would be nice if it worked the same way as the easystyler expands vendor prefixes.

Uncaught TypeError: Cannot call method 'toString' of undefined
com.humboldtjs.utility.Animator.__chain.com.humboldtjs.utility.Animator.animatePropertyToAnimator.js:28
com.luxaflex.advisor.view.pages.typeselector.TypeSelectorComponent.__chain.com.luxaflex.advisor.view.pages.typeselector.TypeSelectorComponent.createElementsTypeSelectorComponent.js:64
com.luxaflex.advisor.view.pages.typeselector.TypeSelectorMediator.__chain.com.luxaflex.advisor.view.pages.typeselector.TypeSelectorMediator.handleNotificationTypeSelectorMediator.js:48
org.puremvc.as3.patterns.observer.Observer.__chain.org.puremvc.as3.patterns.observer.Observer.notifyObserverObserver.js:53
org.puremvc.as3.core.View.__chain.org.puremvc.as3.core.View.notifyObserversView.js:76
org.puremvc.as3.patterns.facade.Facade.__chain.org.puremvc.as3.patterns.facade.Facade.notifyObserversFacade.js:184
org.puremvc.as3.patterns.facade.Facade.__chain.org.puremvc.as3.patterns.facade.Facade.sendNotificationFacade.js:176
org.puremvc.as3.patterns.observer.Notifier.__chain.org.puremvc.as3.patterns.observer.Notifier.sendNotificationNotifier.js:28
com.luxaflex.advisor.commands.ExternalDataLoadedCommand.__chain.com.luxaflex.advisor.commands.ExternalDataLoadedCommand.onConfigLoadCompleteExternalDataLoadedCommand.js:62
nLuxaflex.js:150
com.humboldtjs.events.EventDispatcher.__chain.com.humboldtjs.events.EventDispatcher.dispatchEventEventDispatcher.js:95
com.humboldtjs.net.PrefixLoader.__chain.com.humboldtjs.net.PrefixLoader.doCallbackPrefixLoader.js:112
com.humboldtjs.net.PrefixLoader.__chain.com.humboldtjs.net.PrefixLoader.onCallbackPrefixLoader.js:119
(anonymous function)

**Comment by humboldtjs** [comment]
It DOES do vendor prefixes, however not correctly (apparently) and would not do it for "opacity" since that is a special case... to get that working you need to do stuff with the "filter" property as well to get it working on older Internet Explorer browsers. So that is what it was attempting to do, and worked when you use just "opacity" without the minus. However will change this to make this to work both ways, and fix the error you're getting...

**Comment by humboldtjs** [comment]
And this has been fixed! :)
