### ISSUE TITLE
Animator class reference to Sine is broken in .swc

### ISSUE THREAD

**Issue by martijndeb** [humboldtjs/HumboldtJSLibrary#3]
If we link to the .swc file for the library the "compiler" complains with the following error:

```
 [java] Cannot find file: com/humboldtjs/utility/Sine.as
 [java] Dependency:  com.humboldtjs.utility.Sine*
 [java] Java Result: 1
```

This is probably because of the Sine reference, which makes it look in the same namespace, but actually it's namespaced in .easing. However when linking to the sources this doesn't happen (check out the project -> add the source instead of the library as an compiler argument).

This is a major inconvenience while developing, but easily workarounded.

**Comment by humboldtjs** [comment]
Has been fixed. Was related to an error in the compiler which did auto completing a package's local namespace incorrectly. It saw every class in a sub package as belonging to the same package, which caused an import conflict with the Sine class.

**Comment by martijndeb** [comment]
Luxe business
