### ISSUE TITLE
Second eventlistener not being called.

### ISSUE THREAD

**Issue by ManolitoSnell-INDG** [humboldtjs/HumboldtJSLibrary#8]
**Example**

``` actionscript
theWindow.addEventListener("keypress", eventFunction(this, onWindowKeyPress1), false); 
theWindow.addEventListener("keypress", eventFunction(this, onWindowKeyPress2), false); 
```

**Expected Result**
All eventhandlers to be called.

**Actual Result**
`onWindowKeyPress2` is never being called.

**Comment by humboldtjs** [comment]
Can you add a complete test-case? As I'm reading it now it seems like you're doing it on an HTMLElement and as such it wouldn't be a HJS issue but a browser engine issue right?
