### ISSUE TITLE
HTMLElement setPercentWidth/Height does not accept fractions.

### ISSUE THREAD

**Issue by ManolitoSnell-INDG** [humboldtjs/HumboldtJSLibrary#9]
**Example**

``` actionscript
HTMLElement.setPercentWidth(12.65);
```

**Expected result**
The DOM element to have a width of `12.65%`.

**Actual result**
The DOM element has a width of `13%`.

**Comment by humboldtjs** [comment]
Latest HJSLibrary fixes this.
